### ISSUE TITLE
Can not run example

### ISSUE THREAD

**Issue by dao-wkm** [aarajput/flutter_form_validators#2]
Thanks for reading.

<img width="861" alt="Screen Shot 2020-02-26 at 11 30 07 AM" src="https://user-images.githubusercontent.com/42726313/75312122-96af7100-588b-11ea-9b44-d1d145a01307.png">

**Comment by aarajput** [comment]
Which error are you getting?

**Comment by dao-wkm** [comment]
@aarajput please check my edited issue

**Comment by aarajput** [comment]
have you tried running command `pod install` in ios folder ?

**Comment by dao-wkm** [comment]
@aarajput it's work, thank you
