### ISSUE TITLE
Please fix your broken email validator!

### ISSUE THREAD

**Issue by RandalSchwartz** [aarajput/flutter_form_validators#4]
No, please don't use this so-called "regex email validation".

I can think of a few email addresses that are perfectly valid that do not match that regex. When you want to validate an email address, please do not use a hand-rolled (or even copy-n-pasted) regex.

Instead, use (Dart) https://pub.dev/packages/email_validator (or Perl) https://metacpan.org/pod/Mail::RFC822::Address, which properly implements the RFC822 (et. seq.) address according to the rules in the RFC.

(Jokingly...) Or, cut-n-paste this one (and only this one): http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html. Don't forget to remove the newlines from that 1400-char monster. :)

**Comment by aarajput** [comment]
@RandalSchwartz !! Can you please send me example of email that you think is valid but this plugin is giving you an error?

**Comment by aarajput** [comment]
I don't think current email validation implementation is wrong. If someone want custom email validator, he can use regex. Thats why i am closing this issue.
