### ISSUE TITLE
broken 

### ISSUE THREAD

**Issue by faithyoussef** [aarajput/flutter_form_validators#5]
hello, 
the flutter plugin isnot wroking because the textfield cannot take it in.
just as below
 TextField(
                keyboardType: TextInputType.numberWithOptions(
                decimal: true,
                signed: true,
              ),
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: ' confirm password',
                    errorText: _passwordError),
               //of i add the below line it says an error which the textfield doesnot recognize // validator: Validators.email('Invalid password'),
![validateerror](https://user-images.githubusercontent.com/38753427/215349560-b51739e5-1f80-4d8b-a919-7fa95f483a62.png)

                 ),
please respond asap so that i can fix my signup page for an app i am building.
thank you for your time.

**Comment by aarajput** [comment]
Please use TextFormField instead of TextField
