### ISSUE TITLE
please update and add better phone number validator as well

### ISSUE THREAD

**Issue by fisforfaheem** [aarajput/flutter_form_validators#6]
kindly support flutter

**Comment by aarajput** [comment]
There is no specific regex for phone number validation.
Feel free to create PR if you have one in mind.

**Comment by fisforfaheem** [comment]
Kindly atleast update for flutter 3.13

**Comment by aarajput** [comment]
@fisforfaheem, I will fix it tomorrow. Thanks.

**Comment by fisforfaheem** [comment]
Ok, thanks.

**Comment by fisforfaheem** [comment]
still not updated yet

**Comment by fisforfaheem** [comment]
just include a simple regex for password with length more than 6 as required by firebase

**Comment by aarajput** [comment]
@fisforfaheem , I have published v1.0.1 and update the sdk.

**Comment by aarajput** [comment]
For firebase please use validator [minimum-length](https://pub.dev/packages/wc_form_validators#minimum-length) validator and pass value 6. It will resolve your issue of firebase password validation.

**Comment by fisforfaheem** [comment]
Thanks a lot. Kindly improve and  keep  updated
